apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bharatgpt-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      chunked_transfer_encoding off;
spec:
  rules:
  - host: api.bharatgpt.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bharatgpt-api-svc
            port:
              number: 80
